### ISSUE TITLE
WebApplicationException thrown if REST resource does not exist

### ISSUE THREAD

**Issue by bienenstich** [Mercateo/rest-hateoas-client#4]
Scenario: call a templated link with a value that points to a nonexistent resource.

Expected behaviour: client should return Optional.empty()
Actual behaviour: client throws WebApplicationException.

If the server comes back with a 404 response, OngoingResponseImpl throws a WebApplicationException. 
`if (response.getStatus() >= 300) {
			throw new WebApplicationException(response);
		}`
(OngoingResponseImpl, line 93).

**Comment by JoergAdler** [comment]
Hi. The Optional.empty() return type is reserved for abstinence of the relation. Therefore it behaves like every other relation.

I would prefer to handle templated URLs like every other URL. It is a technical detail, which is not relevant in the level of abstraction of this client.  So a different behavior would be distracting.
