### ISSUE TITLE
Absolute URLs in response's relations required?

### ISSUE THREAD

**Issue by nln42** [Mercateo/rest-hateoas-client#6]
After accessing the root resource at the beginning of a journey subsequent callsWithRel assumes absolute URLs being returned in the response. 

So currently the rest-hateoas-client always assumes absolute URLs or else you'll end up in ProcessingExceptions.

I'm wondering why the ClientStarter doesn't use the host he already knows from accessing the root resource?

**Comment by JoergAdler** [comment]
At the moment, the client always assumes the hrefs in the links to be absolute URls or URI-templates. 

Your assumption, that every resource has to be on the host of the entry resource is not true in some cases.

If one want to support relative URIs, one has to persist the URI of the current resource and put the host from it to the next call. 

Unfortunately, I don't have time to do so. So please feel free, to make a pull request for that issue.

**Comment by JoergAdler** [comment]
closed with #7 

thanks a lot
